### ISSUE TITLE
Ambiguous match in Cucumber steps definitions

### ISSUE THREAD

**Issue by iiezhachenko** [davetron5000/methadone#102]
Hi,
I'm getting error below when trying to run tests. I would like to contribute, but can't even start.

Tried to add guess in Rakefile, to bypass ambiguity, but it didn't helped.
Could you please advice?

```
localhost:methadone ievgen$ rake features
Ambiguous match of "the directory "tmp/newgem" does not exist":

aruba-0.14.1/lib/aruba/cucumber/file.rb:73:in `/^(?:a|the) (?:file|directory)(?: named)? "([^"]*)" does not exist$/'
features/step_definitions/bootstrap_steps.rb:4:in `/^the directory "([^"]*)" does not exist$/'

 (Cucumber::Ambiguous)
```

**Comment by davetron5000** [comment]
weird, it looks like Aruba now has that step: https://github.com/cucumber/aruba/blob/master/lib/aruba/cucumber/file.rb#L73

I think the thing to do is:

- [ ] change this gem to require the version of Aruba that introduced that step (can't tell which one—maybe your git-fu is better than mine?)
- [ ] remove that step definition from methadone
- [ ] build passes?  ➡️  new version

**Comment by davetron5000** [comment]
Fresh build and I'm not seeing this.  Feel free to re-open if you are still having this issue.  NOte that #117 addresses other issues with a modern build.

**Comment by davetron5000** [comment]
NM, I am seeing this locally.

**Comment by davetron5000** [comment]
Once #121 is merged, Cucumber and Aruba will be gone.  I could not get them to work with whatever changes they have made in the past few years.
