### ISSUE TITLE
uninitialized constant Methadone (NameError)

### ISSUE THREAD

**Issue by cdempsey** [davetron5000/methadone#123]
**Steps to Reproduce**
1. Start a new project using Methadone's [README](https://github.com/davetron5000/methadone/blob/master/README.rdoc)
    1. Run `methadone test-app -l mit`
    1. Run `bundle install`
    1. Bundle `bundle exec rake`

**Expected Outcome**
1. Tests run to completion without error

**Actual Outcome**
1. Error `/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/methadone-2.0.0/lib/methadone/test/integration_test_assertions.rb:1:in '<top (required)>': uninitialized constant Methadone (NameError)` is thrown

**Command Line Output**
```
11:15 $ bundle exec rake
Loaded suite /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
.
Finished in 0.000494 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2024.29 tests/s, 2024.29 assertions/s
Traceback (most recent call last):
	10: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
	 9: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	 8: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	 7: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:9:in `each'
	 6: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	 5: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:10:in `require'
	 4: from /Users/cdempsey/Development/Projects/ruby/test-app/test/integration/test_cli.rb:1:in `<top (required)>'
	 3: from /Users/cdempsey/Development/Projects/ruby/test-app/test/integration/test_cli.rb:1:in `require'
	 2: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/methadone-2.0.0/lib/methadone/test/base_integration_test.rb:7:in `<top (required)>'
	 1: from /Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/methadone-2.0.0/lib/methadone/test/base_integration_test.rb:7:in `require_relative'
/Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/methadone-2.0.0/lib/methadone/test/integration_test_assertions.rb:1:in `<top (required)>': uninitialized constant Methadone (NameError)
Did you mean?  Method
rake aborted!
Command failed with status (1): [ruby -I"lib" -I"/Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib" "/Users/cdempsey/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/integration/test_*.rb" ]
/Users/cdempsey/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/Users/cdempsey/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => default => test:integration
(See full trace by running task with --trace)
```

**Environment**
* MacOS: 10.14
* rbenv: 1.1.1
* Ruby: 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
* gem: 2.7.6
* bundler: 1.16.5
* rake: 10.5.0

**Comment by davetron5000** [comment]
Fixed and released in 2.0.1

Thanks for the report!
